---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: bazarr
      version: 10.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v1.0.4
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "closed-caption"
        hosts:
          - host: "downloads.${SECRET_DOMAIN}"
            paths:
              - path: /bazarr
                pathType: Prefix
        tls:
          - hosts:
              - downloads.${SECRET_DOMAIN}
            secretName: "downloads-tls"
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
      movies:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/bigdata/files/video/Movies"
        mountPath: /movies
      tv:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/bigdata/files/video/TV"
        mountPath: /tv
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/data/files/downloads"
        mountPath: /downloads
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 20003
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi