---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-sleep
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 100Mi
