---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: samba
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      # -- Set the container timezone
      TZ: ${TIMEZONE}
    configmap:
      config:
        enabled: true
        data:
          config.yml: |
            auth:
              - user: smbuser
                group: smbuser
                uid: 101
                gid: 101
                password: smbuser
            global:
              - "force user = smbuser"
              - "force group = smbuser"
              - "create mask = 0644"
              - "directory mask = 0755"
            share:
              - name: Sleep
                path: /sleep
                browsable: yes
                readonly: no
                guestok: yes
                comment: "sleepy tracks"
                veto: yes

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_SAMBA_ADDR}"
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 445
          netbios:
            enabled: true
            protocol: TCP
            port: 139

    persistence:
      sleep:
        enabled: true
        existingClaim: samba-sleep

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
