---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: samba
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      # -- Set the container timezone
      TZ: America/Chicago
      SHARE1: Sleep;/samba-sleep;yes;no
      PERMISSIONS: true

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_SAMBA_ADDR}"
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 445
          netbios:
            enabled: true
            protocol: TCP
            port: 139

    persistence:
      sleep:
        enabled: true
        existingClaim: samba-sleep

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
