---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr-nightly
      tag: v1.0.0.2515
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "downloads.${SECRET_DOMAIN}"
            paths:
              - path: /lidarr
                pathType: Prefix
        tls:
          - hosts:
              - downloads.${SECRET_DOMAIN}
            secretName: "downloads-tls"
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      music:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/data/files/music"
        mountPath: /music
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/data/files/downloads"
        mountPath: /downloads
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 20003
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi
