# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:E3O0FlqH5pCusXXIcaEO0bGihORb2hJLUOS3P7eT0JlEe3F7f6DVMe0RTnvryu7r4ogUKl/AonCxZtbOC4OtZDJ+ohh7Ip/NLZ/AGtqrln2qfJ23zF+90WkQvok/RZAPQCO9aYDOPfdSErjiUqE/Fk8pJA9an8RAHNhxIgrRZQ==,iv:Yfgs1jreLrSmZWiHUTgjuk6rFUZ0+fztbXPvPvpCis8=,tag:/Xmay6TUBmNHuQcvQgDH0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kln2st0xaydsa0xsrsnk62qhhvwqzyyt9a7kj60py3ah76p0cgtsuk0wh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTDdVZnZSSXVQRm5odEVz
            VG54VjVKQ293UVcxaEJmMmtRNlJ1NWpLazBzCnRBcWNobVFKaVM3TzJ2RnFJZm9j
            ak1KVWIyVGlHNnc0NnJBRGEzMGdNWTgKLS0tIGpjS0h5eTdGejUxaWtIdmMvaS80
            YnNZMGh1b2ZHbW02eWpXOFNjb1NKTFUKQp4a/YO57U//XFbM6MYEUyjVuQe1F458
            kGaeZlLqCLb2qNOYc+zygZf+5cB16Yn78uF20YtHoEwzGyPG1GbEDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-20T02:50:49Z"
    mac: ENC[AES256_GCM,data:dTazhruUzWJnLp9iX3oPRsV1mP8zc6FnqfLgL3bCRweagSx5DHEZz3/XneXfhAuFanjLBu3YlyA/GnWVrWNlCZP43mxksDE01dWDi7CNxYKxO6vdR4eEXayjodUCBf3Elbj4IqqSZu84XoCnn6YaEYVY73NWQJm2yo9ok7yY3K8=,iv:k1oxk2QKymbS5tfY/NfrL3yONNaIS/z2TxuNBhc4FUM=,tag:c17LOhMKjZFGyueUKqZ7pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
