---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    replicas: 1
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/appName: "uptime-kuma"
          hajimari.io/enable: "true"
          hajimari.io/icon: "sort-clock-descending-outline"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "uptime.${SECRET_DOMAIN}"
            secretName: "uptime-kuma-tls"
    persistence:
      data:
        enabled: true
        existingClaim: uptime-kuma
