---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-cousins-iscsi
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  iscsi:
     targetPortal: ${NAS}:3260
     iqn: iqn.2022-04.k8s.iscsi:mc-cousins
     lun: 1
     fsType: 'ext4'
     readOnly: false
