---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-cousins-minecraft-bedrock
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
