---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channels-dvr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
