---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-beeplains-minecraft
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
