---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-beeplains
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: "4.0.0"
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    extraEnv:
      ALLOW_FLIGHT: "TRUE"
      ENABLE_AUTOPAUSE: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      TZ: "${TIMEZONE}"
      REMOVE_OLD_MODS: "TRUE"
      MODPACK: "https://myrepos.${SECRET_DOMAIN_B}/misc/mc-server-mods.zip"
      REMOVE_OLD_VANILLATWEAKS: "TRUE"
      VANILLATWEAKS_SHARECODE: "pL7CFT"
      ENFORCE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "false"
    minecraftServer:
      eula: "TRUE"
      type: "FABRIC"
      # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
      version: "1.18.1"
      # One of: peaceful, easy, normal, and hard
      difficulty: hard
      # A comma-separated list of player names who should be admins.
      ops: "${MINECRAFT_OPS}"
      # Max connected players.
      maxPlayers: 10
      # This sets the maximum possible size in blocks, expressed as a radius, that the world border can obtain.
      maxWorldSize: 29999984
      # Max view distance (in chunks)
      # The maximum number of milliseconds a single tick may take before the server watchdog stops the server with the message. -1 disables this entirely.
      maxTickTime: "-1"
      viewDistance: 18
      # Define this if you want a specific map generation seed.
      levelSeed: "-152246528000119912"
      # One of: creative, survival, adventure, spectator
      gameMode: survival
      # Message of the Day
      motd: "Welcome to Bee Plains"
      # If true, enable player-vs-player damage.
      pvp: true
      # One of: DEFAULT, FLAT, LARGEBIOMES, AMPLIFIED, CUSTOMIZED
      levelType: DEFAULT
      # When levelType == FLAT or CUSTOMIZED, this can be used to further customize map generation.
      # ref: https://hub.docker.com/r/itzg/minecraft-server/
      generatorSettings:
      # force re-download of server file
      forceReDownload: false
      # Check accounts against Minecraft account service.
      onlineMode: true
      # If you adjust this, you may need to adjust resources.requests above to match.
      memory: 2048M
      # General JVM options to be passed to the Minecraft server invocation
      jvmOpts: ""
      # Options like -X that need to proceed general JVM options
      jvmXXOpts: ""
      serviceType: LoadBalancer
      loadBalancerIP: "${SVC_MC_JAVA_2_ADDR}"
      externalTrafficPolicy: Local
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-beeplains-minecraft
    resources:
      requests:
        memory: 2048Mi
        cpu: 1000m
