# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FyfDCT8DOfB84Eop2vS/,iv:kKJ1hREZm2gv2H1ru+d4D7VRpZCoPK/6rLfXU+HdOkw=,tag:d1cM7NJHWh8W4dzfodnNAg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVkuliTjTnIYaFE4YORtmRH2/iz3,iv:CL/TqyywPXnevutLgg58gRuJk6Esl376q4kToLVEQho=,tag:mGcm5+g73qTsrJ1IEVzyUw==,type:str]
    SECRET_BONOB_KEY: ENC[AES256_GCM,data:KLhT4zvZ0+zPgI3DwzWhBLehT85niNogsEy90/Qk,iv:qHiEyIEWOKJ8SEfarIVLwgOqFQ2sI+n6mnrJ9obxSxQ=,tag:UQ0BrM93tfNlaBCNKtm41Q==,type:str]
    SECRET_MINIO_TOKEN: ENC[AES256_GCM,data:AgTdoXS2xZU9/Oy7vTa365Oil8kfCECxtkhYfkjImdOWgapRwas7nbH3JiGwFAFQNjjUDXtQIeoe/PPVhPAQ10NEzK5QmEARAWgBHPJSPe1XGwmkSmQOh5dIqmH0AkzxFXVoLuCUnA==,iv:ap7l39gkFwPXKdjGg/qePCtKUKH6LxXk3RdmOiFdnhU=,tag:ovrLyG25h2FZNUAVKpeUhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kln2st0xaydsa0xsrsnk62qhhvwqzyyt9a7kj60py3ah76p0cgtsuk0wh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd3puaXFMaUIvMGJ0S2Jj
            OEkrcHJlV2FERk9lQUR6MFdpWm5KeEVDMW1JCkpkRFdDWTlXNy9PTGVEU09ibVkv
            eXM4WGNrRkNxckR6SjRvOFF4NmlHSUUKLS0tIHdqSHROalVEMVBFeFlJWHRweUVT
            RTIzYW14b3FwMndFVjdWeVZlL3BvYTgK4NmEp9B/6bE+P7L0gw5VGqDIoRuaSE0e
            F1IhVcF3s0mzC2q1Vs2V0CuKVxz66pUg78zJCXzvPTWzArZwSC27zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-29T03:14:09Z"
    mac: ENC[AES256_GCM,data:HKFtkfGHBoKUI3xCqJ8r0V7nVSdbfdJ38KPappjTj4pY3+0e9YqTM9vaujqkPKw24gx6goFq0WosWh1aEVRDriviokGajalWwZ9GeTUNwJBjAdj41cc+ldU0V/79Si81wSLnLgydul2PGiohRngenN60iDYRi0MdeqQMz5zYQmw=,iv:1VXFAho8w80KyiQ9nKmZJh8TVKoGmxYkNEjJDld7ad4=,tag:nZaWFsVBM+CdlhKkVl8Q+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
