---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 15.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1342
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
        hosts:
          - host: "downloads.${SECRET_DOMAIN}"
            paths:
              - path: /sonarr
                pathType: Prefix
        tls:
          - hosts:
              - downloads.${SECRET_DOMAIN}
            secretName: "downloads-tls"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      tv:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/bigdata/files/video/TV"
        mountPath: /tv
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/data/files/downloads"
        mountPath: /downloads
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 20003
