---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: navidrome
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: deluan/navidrome
      tag: 0.43.0
    env:
      TZ: "America/Chicago"
      ND_LOGLEVEL: info
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_MUSICFOLDER: /music
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "music"
        hosts:
          - host: "navidrome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - navidrome.${SECRET_DOMAIN}
            secretName: "navidrome-tls"
    persistence:
      config:
        enabled: true
        existingClaim: navidrome
      music:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/data/files/music"
        mountPath: /music
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 20003
