---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: benji-pg-backup-pv
spec:
  storageClassName: benji-pg-backup
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NAS_ADDR}"
    path: /data/backup/benji-pg
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benji-pg-backup
  namespace: backup-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: benji-pg-backup
  resources:
    requests:
      storage: 100Mi

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: backup-system
spec:
  # Backup the database every day at 5AM
  schedule: "00 05 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:12
              command: ["/bin/sh"]
              args:
                [
                  "-c",
                  'pg_dump -U benji -h benji-postgresql-headless benji > /var/backups/pgsql/backup-$(date +"%m-%d-%Y-%H-%M").sql',
                ]
              env:
                - name: PGPASSWORD
                  value: secret
              volumeMounts:
                - mountPath: /var/backups
                  name: postgres-storage
          restartPolicy: Never
          volumes:
            - name: postgres-storage
              persistentVolumeClaim:
                claimName: benji-pg-backup
