# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-credentials
    namespace: backup-system
data:
    key: ENC[AES256_GCM,data:sxeBHIQ=,iv:S/qW9UpSulv3kO/NkXxBo151xvfNddzKWEq73X3XczI=,tag:/HT+i0hlpHVLyJ3Xp9k7kg==,type:str]
    secret: ENC[AES256_GCM,data:XDoZteupwQJFnSAi11SYaTIsNAdr3KWI,iv:JKSt6DoG35Tx5189ZGWQm+qOBajYeP3id3ZBERutXzs=,tag:tkuet5EAquRfP64una6NKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kln2st0xaydsa0xsrsnk62qhhvwqzyyt9a7kj60py3ah76p0cgtsuk0wh9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNHkyblVJY1ovaWlnMk94
            YkRuS0hXNlZwbmRCRXU4VDlXL3pIUzc4ajNnCmJxdXJuMkVJOHBaakpGd0ZsMUkr
            TS83K0g0Y0Vmck9LaHZkRWc1cHlFUXcKLS0tIDNWU2t6cUJBeHA5Qnlnb0h2eG5y
            WklFTXVSOEZLSGpFSEowWUYwbkJiazAK8GH7GQmf1kOC9MLi9GPa6AVFA23PAY9x
            Tf3XpJFMX5KThMAQ5TUJR+yVD1oyzheV2olLAhjTRUPGgjuCvVOnBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T23:14:30Z"
    mac: ENC[AES256_GCM,data:DRXTEIKmVDT2AdVu9tp7Xxwj/tDFXiTNp4fIwExbofqXC6/j7UUtpdYyE9M86su0fLX5huW8o1soJ553hHc1Jr7K9FhEGwlvs8jueq+cyP2Ouql9Mb0hcXzlmcaCGvry+b/EuWQFVqBTPInyoCbBwezBtQKBsvABNJ5OwIGCSYM=,iv:mW1+xXNQguIp3Em5BAu36H5PEUq9+OM468LRVCAV4LM=,tag:PyvJWmrvgaKr9Xf+VHH/zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
