---
- name: Update max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "65536"
    state: present
    sysctl_file: /etc/sysctl.d/98-kubernetes-fs.conf

- name: Disable swap at runtime
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap on boot
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
