---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sabnzbd
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.5.3
    env:
      TZ: "${TIMEZONE}"
      HOST_WHITELIST_ENTRIES: "downloads.${SECRET_DOMAIN}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "download"
        hosts:
          - host: downloads.${SECRET_DOMAIN}
            paths:
              - path: /sabnzbd
                pathType: Prefix
        tls:
          - hosts:
              - downloads.${SECRET_DOMAIN}
            secretName: "downloads-tls"
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/data/files/downloads"
        mountPath: /downloads
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 20003
