---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: v1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    persistence:
      defaultClass: false
    longhornManager:
      tolerations:
        - key: "nodetype"
          operator: "Equal"
          value: "longhorn"
          effect: "NoSchedule"
    longhornDriver:
      tolerations:
      - key: "nodetype"
        operator: "Equal"
        value: "longhorn"
        effect: "NoSchedule"
    longhornUI:
      nodeSelector:
        nodetype: longhorn
      tolerations:
      - key: "nodetype"
        operator: "Equal"
        value: "longhorn"
        effect: "NoSchedule"
    defaultSettings:
      backupTarget: s3://longhorn-backups@us-east-1/
      backupTargetCredentialSecret: minio-secret
      createDefaultDiskLabeledNodes: true
      guaranteed-engine-manager-cpu: 25
      guaranteed-replica-manager-cpu: 25
      replicaAutoBalance: best-effort
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      taintToleration: "nodetype=longhorn:NoSchedule"