---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: v1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    persistence:
      defaultClass: false
    longhornManager:
      tolerations:
        - key: "node-role.kubernetes.io/longhorn"
          operator: "Exists"
          effect: "NoSchedule"
    longhornDriver:
      nodeSelector:
        node-role.kubernetes.io/longhorn: "true"
      tolerations:
        - key: "node-role.kubernetes.io/longhorn"
          operator: "Exists"
          effect: "NoSchedule"
    longhornUI:
      nodeSelector:
        node-role.kubernetes.io/longhorn: "true"
      tolerations:
        - key: "node-role.kubernetes.io/longhorn"
          operator: "Exists"
          effect: "NoSchedule"
    defaultSettings:
      backupTarget: s3://longhorn-backups@us-east-1/
      backupTargetCredentialSecret: minio-secret
      createDefaultDiskLabeledNodes: true
      guaranteed-engine-manager-cpu: 25
      guaranteed-replica-manager-cpu: 25
      replicaAutoBalance: best-effort
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      taintToleration: "node-role.kubernetes.io/longhorn:NoSchedule"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: "longhorn-tls"
