---
name: Schedule - Renovate

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "true"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"

jobs:
  renovate-helm-releases:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Verify Renovate Configuration
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2

      - name: Renovate Helm Releases
        uses: k8s-at-home/renovate-helm-releases@v1
        with:
          cluster-path: "./cluster"
